---
# handlers file for conesphere.mail.spamassassin
- name: restart_spampd
  shell: |
    rcctl enable spampd
    rcctl restart spampd || ( sleep 20 ; rcctl restart spampd ) 
- name: restart_smtpd
  shell: |
    rcctl enable smtpd
    rcctl restart smtpd

